application: odur
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheet
  static_dir: stylesheet

- url: /favicon.ico
  static_dir: favicon.ico

- url: /image
  static_dir: image

- url: .*
  script: main.py
